### ISSUE TITLE
Move non RxJava stub classes to an independent artifact

### ISSUE THREAD

**Issue by cbornet** [salesforce/grpc-java-contrib#60]
Working on porting rxgrpc to Spring's Reactor, I realized that some of the rxgrpc classes don't depend on RxJava and could be mutualized between all reactive-streams implementations (RxJava, Reactor, Akka-streams, ...)
Those are : CancellableStreamObserver, RxExecutor, RxStreamBackpressureOnReadyHandler, RxStreamObserverPublisher
Maybe some others could also be generified.

So it would be great to have these in an artifact independant of the underlying reactive implementation.

**Comment by cbornet** [comment]
The generator could also have a common mother class + mustache file as the diff between implementations would be mostly an import and maybe the class/method prefix.

**Comment by rmichela** [comment]
> Maybe some others could also be generified.

Perhaps. Do you have a working POC using these classes? I'm hesitant to move these classes prematurely since they weren't written with other reactive technologies in mind. 

If POC work with other reactive technologies shows they can be used with no or minimal modification, we could move them up into a contrib/reactive namespace under grpc-java-contrib.

**Comment by cbornet** [comment]
My Reactor port is in good way : I have everything working except the TCK.
I copied the classes above as-is without modification so it would be great to have them in contrib/reactive.

As for the Reactor gen, do you prefer that I PR on this repo or that I maintain it in another one (most of the code is yours, I only did a portage) ?

**Comment by cbornet** [comment]
See my branch [here](https://github.com/cbornet/grpc-java-contrib/tree/reactor). I now have everything working (the changes for the TCK were very straight-forward).

**Comment by rmichela** [comment]
This looks great! I was thinking of splitting the rx packages off from the contrib stuff into its own repo, since they change at different rates and for different reasons. Also, the rx tests take so long to validate everything.

A proposed layout would look like:
* reactive-grpc-common
* rx-java
  * rx-grpc
  * rx-grpc-stub
  * rx-grpc-test
  * rx-grpc-tck
* reactor
  * reactor-grpc
  * reactor-grpc-stub
  * reactor-grpc-test
  * reactor-grpc-tck

**Comment by cbornet** [comment]
👍 
I let you create it. Just give me credit for the reactor part 😄

**Comment by cbornet** [comment]
@rmichela Do you need help on this ? If you create the repo, I can do PRs.

**Comment by rmichela** [comment]
I'm working on creating the repo now.

**Comment by rmichela** [comment]
@cbornet I've created the new repo and set you up as a collaborator. You can now move your code and do the refactoring you need to get a common base module.

**Comment by cbornet** [comment]
:+1:

**Comment by rmichela** [comment]
RxGrpc can now be found at https://github.com/salesforce/reactive-grpc. Continued work on this issue will happen there.
